scrape.js: Deleted duplicated API call
coala/gci-leaders pull request #133
Opened 2018-01-06 14:44 UTC by sthkindacrazy

The created_issues were called twice unnecessarily. This commit deleted one to remove duplicated call

Closes https://github.com/coala/gci-leaders/issues/116

2018-01-09 17:22 UTC, andrewda approved these changes

2018-01-09 17:23 UTC, andrewda commented
Squash your commits into one. You shouldn't have a merge commit.

2018-01-10 18:11 UTC, wisn approved these changes

2018-01-11 08:18 UTC, thealphadollar requested changes
@sthkindacrazy Please follow the commit message guidelines. Also, use present tense in the text you write.

http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

2018-01-11 12:26 UTC, blazeu commented
@wisn Did he take the GCI task?

2018-01-27 18:16 UTC, jayvdb requested changes
Squash your commits

2018-09-10 04:15 UTC, jayvdb commented
@gitmate-bot rebase

2018-09-10 04:26 UTC, jayvdb approved these changes

2018-09-10 04:26 UTC, jayvdb commented
ack https://github.com/coala/gci-leaders/pull/133/commits/2b3f8367fa525dbdfe35742a3ea4ca5044fbffd0

2018-09-10 04:26 UTC, jayvdb commented
@gitmate-bot ff

2018-09-10 04:29 UTC, merged