scrape.js: Deleted duplicated API call
coala/gci-leaders pull request #146
Opened 2018-02-13 13:30 UTC by Ananthavijay

The created_issues were called twice unnecessarily. This commit deleted one to remove duplicated call.
This PR Fixes : https://github.com/coala/gci-leaders/issues/116

2018-05-03 05:47 UTC, IpshitaC requested changes
Hi @Ananthavijay 
Could you please modify your commit message, according to our guidelines [here](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html). Currently, your commit is not very self-explanatory and doesn't have a body and issue reference. Please make the necessary changes.

Also, builds are failing and you can check the logs [here](https://travis-ci.org/coala/gci-leaders/jobs/340947291).

Please update your PR accordingly.

2018-05-04 04:43 UTC, jayvdb commented
@Ananthavijay, please fix your commit message as @IpshitaC requested.

2018-05-04 13:32 UTC, Ananthavijay commented
why the build fails?

2018-06-15 04:11 UTC, jayvdb commented
@Ananthavijay , builds fail because of lots of reasons.  Other things break occasionally and we need to fix them.

Please fix your commit message so we can put this into the queue to be merged whenever the builds are not broken.

2018-09-10 04:32 UTC, jayvdb commented
Abandoned PR, so I fixed and merged  https://github.com/coala/gci-leaders/pull/133

2018-09-10 04:32 UTC, closed without merging