lib/scrape.js: Add year variable
coala/gci-leaders pull request #157
Opened 2018-10-08 07:58 UTC by utkarsh2102

This fixes the year by creating a GCI_YEAR variable.

Fixes https://github.com/coala/gci-leaders/issues/153

2018-10-08 08:02 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;438499281">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][08:01:00] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][08:01:00] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][08:01:03] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][08:01:03] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][08:01:04] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][08:01:04] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
[DEBUG][08:01:04] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][08:01:04] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][08:01:04] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][08:01:04] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-08 09:41 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;438536752">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][09:39:56] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][09:39:56] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][09:39:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][09:39:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][09:40:00] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][09:40:00] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
[DEBUG][09:40:00] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][09:40:00] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][09:40:00] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][09:40:00] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-08 09:52 UTC, pandyamarut approved these changes
Hopefully this changes works. 
@jayvdb Look into it.

2018-10-08 09:56 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;438543025">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][09:55:56] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][09:55:56] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][09:55:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][09:55:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][09:55:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][09:55:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
[DEBUG][09:55:59] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][09:56:00] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][09:56:00] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][09:56:00] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-08 10:06 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;438548214">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][10:05:52] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][10:05:53] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][10:05:55] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][10:05:55] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][10:05:56] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][10:05:56] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
[DEBUG][10:05:56] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][10:05:56] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][10:05:56] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][10:05:56] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-13 15:56 UTC, li-boxuan requested changes

2018-10-13 15:56 UTC, li-boxuan commented on lib/scrape.js
> +        `${GCI_API_BASE}/program/${GCI_YEAR}/organization/?status=2`)
Please make CI happy. See https://travis-ci.org/coala/gci-leaders/builds/438548213#L1059

2018-10-13 18:06 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;441064591">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:05:24] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][18:05:24] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][18:05:27] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][18:05:27] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][18:05:27] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][18:05:27] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
[DEBUG][18:05:27] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][18:05:28] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][18:05:28] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][18:05:28] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-23 03:35 UTC, jayvdb requested changes
Please squash your commits.
We only want one commit per atomic change.

2018-10-23 03:35 UTC, jayvdb commented on lib/scrape.js
> +const GCI_YEAR = '2018'
the year needs to be dynamic.

2018-10-23 11:20 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445064477">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][11:18:58] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][11:18:59] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][11:19:02] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:19:02] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][11:19:02] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:19:03] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
[DEBUG][11:19:03] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][11:19:03] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][11:19:03] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][11:19:03] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-23 11:20 UTC, utkarsh2102 commented
Sure @jayvdb.
I'll use the `(new Date()).getFullYear()` function to make it dynamic.

2018-10-23 11:40 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445072733">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][11:39:50] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][11:39:50] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][11:39:51] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:39:51] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][11:39:51] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:39:51] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
[DEBUG][11:39:51] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][11:39:52] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][11:39:52] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][11:39:52] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:39:52] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cach [...]

2018-10-23 11:45 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445074504">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][11:43:59] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][11:43:59] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][11:44:02] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:44:02] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][11:44:02] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:44:02] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
[DEBUG][11:44:02] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][11:44:03] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][11:44:03] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][11:44:03] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-23 11:54 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445078939">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][11:53:49] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][11:53:49] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][11:53:52] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:53:52] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][11:53:53] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][11:53:53] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
[DEBUG][11:53:53] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][11:53:53] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][11:53:53] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][11:53:53] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-23 12:08 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445084936">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][12:07:32] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][12:07:32] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][12:07:35] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][12:07:35] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][12:07:35] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][12:07:35] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][12:07:35] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
[DEBUG][12:07:36] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][12:07:36] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][12:07:36] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][12:07:36] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-23 12:25 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445092004">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][12:23:50] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][12:23:50] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][12:23:53] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][12:23:53] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][12:23:53] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][12:23:54] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Use of change_line method is deprecated. Instead use modify_line method, without the original_line argument
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
|----|    | /home/travis/build/coala/gci-leaders/lib/scrape.js
|    |++++| /home/travis/build/coala/gci-leaders/lib/scrape.js
| 105| 105| async function fetchOrgs() {
| 106| 106|   const res = await fetch(
| 107| 107|     `${GCI_API_BASE}/program/${GCI_YEAR}/organization/?status=2`)
| 108|    |-    
|    | 108|+
| 109| 109|   const { results } = await res.json()
| 110| 110|   return results
| 111| 111| }
[INFO][12:23:54] Applied 'ShowPatchAction' on 'lib/scrape.js' from 'SpaceConsistencyBear'.
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
[DEBUG][12:23:54] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][12:23:54] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][12:23:54] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][12:23:54] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/bu [...]

2018-10-23 12:30 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;445094705">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][12:29:22] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][12:29:23] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][12:29:25] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][12:29:26] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][12:29:26] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][12:29:26] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Use of change_line method is deprecated. Instead use modify_line method, without the original_line argument
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
[DEBUG][12:29:26] Running bear SpaceConsistencyBear...
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
|----|    | /home/travis/build/coala/gci-leaders/lib/scrape.js
|    |++++| /home/travis/build/coala/gci-leaders/lib/scrape.js
| 105| 105| async function fetchOrgs() {
| 106| 106|   const res = await fetch(
| 107| 107|     `${GCI_API_BASE}/program/${GCI_YEAR}/organization/?status=2`
| 108|    |-  )    
|    | 108|+  )
| 109| 109|   const { results } = await res.json()
| 110| 110|   return results
| 111| 111| }
[INFO][12:29:26] Applied 'ShowPatchAction' on 'lib/scrape.js' from 'SpaceConsistencyBear'.
Executing section all.linelength...
[WARNING][12:29:26] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][12:29:26] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][12:29:26] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/trav [...]

2018-10-23 13:00 UTC, li-boxuan requested changes
Your commit message has a typo.

2018-10-23 13:00 UTC, li-boxuan commented on lib/scrape.js
> +    `${GCI_API_BASE}/program/${GCI_YEAR}/organization/?status=2`
Please add logic: If this address is invalid, then try the previous year.
As https://github.com/coala/gci-leaders/issues/153#issue-358459483 says, on Jan 1 2019, the website still needs to be using 2018, and should keep using 2018 until the 2019 org data is more valid.

2018-10-24 18:55 UTC, utkarsh2102 commented on lib/scrape.js
> +    `${GCI_API_BASE}/program/${GCI_YEAR}/organization/?status=2`
Oh, okay.
Working on it.

2018-10-25 18:15 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;446302374">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:14:32] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][18:14:33] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][18:14:36] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][18:14:36] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][18:14:36] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][18:14:36] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
[DEBUG][18:14:36] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][18:14:36] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][18:14:36] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][18:14:36] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-25 19:05 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;446323381">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][19:04:24] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][19:04:24] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][19:04:27] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:04:27] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][19:04:27] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:04:27] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:27] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
[DEBUG][19:04:28] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][19:04:28] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][19:04:28] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][19:04:28] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-25 19:39 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;446336670">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][19:38:39] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][19:38:40] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][19:38:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:38:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][19:38:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:38:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
[DEBUG][19:38:43] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][19:38:44] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][19:38:44] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][19:38:44] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-25 19:47 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;446340139">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][19:46:40] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][19:46:40] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][19:46:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:46:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][19:46:44] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:46:44] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
[DEBUG][19:46:44] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][19:46:44] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][19:46:44] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][19:46:44] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-25 21:08 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;446375188">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][21:07:06] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][21:07:06] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][21:07:09] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][21:07:09] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][21:07:10] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][21:07:10] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
[DEBUG][21:07:10] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][21:07:10] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][21:07:10] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][21:07:10] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-l [...]

2018-10-25 21:16 UTC, TravisBuddy commented
## Travis tests have failed

Hey @utkarsh2102,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;446379052">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][21:15:06] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][21:15:07] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][21:15:09] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][21:15:09] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][21:15:10] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][21:15:10] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Use of change_line method is deprecated. Instead use modify_line method, without the original_line argument
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
[DEBUG][21:15:10] Running bear SpaceConsistencyBear...
|    | [NORMAL] SpaceConsistencyBear:
|    | Line contains following spacing inconsistencies:
|    | - Trailing whitespaces.
|----|    | /home/travis/build/coala/gci-leaders/lib/scrape.js
|    |++++| /home/travis/build/coala/gci-leaders/lib/scrape.js
| 113| 113|   const lastYearApi = `${GCI_API_BASE}/program/${year - 1}/`
| 114| 114|   const { results } =
| 115| 115|     res.status != 200 ? (await fetch(lastYearApi)).json() : await res.json()
| 116|    |-    
|    | 116|+
| 117| 117|   return results
| 118| 118| }
| 119| 119| 
[INFO][21:15:10] Applied 'ShowPatchAction' on 'lib/scrape.js' from 'SpaceConsistencyBear'.
Executing section all.linelength...
[WARNING][21:15:10] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][21:15:10] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][21:15:10] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/bu [...]

2018-10-26 03:44 UTC, jayvdb commented
fwiw, the netlify build is failing in `node ./lib/scrape.js` with `4:49:43 AM: (node:1600) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'repositories' of null` . very likely this is an unrelated problem, but we'll need to get it fixed too.

2018-10-26 06:52 UTC, utkarsh2102 commented
Yes, @jayvdb.
Moreover, I think @li-boxuan pulled my changes and made a PR(https://github.com/coala/gci-leaders/pull/161), too.
I think that'd resolve the problem.

2018-10-26 15:48 UTC, jayvdb requested changes
The year on the front page is still 2017.

2018-10-27 08:58 UTC, li-boxuan approved these changes
LGTM ;)
We still have hard-coded year number in i18n files, but we can tackle that later.

2018-10-27 09:02 UTC, li-boxuan commented on lib/scrape.js
> +  year -= 1
This looks ugly :P 
```javascript
const year = new Date().getFullYear()
const lastYear = year - 1
```
is slightly better IMO

2018-10-27 09:04 UTC, li-boxuan commented on lib/scrape.js
> +  year -= 1
Nvm it is working anyway, if there is improvement we can do later

2018-10-27 09:08 UTC, merged