Adds pnpm as new package manager
coala/gci-leaders pull request #170
Opened 2018-11-06 14:41 UTC by SerekKiri

package.json --> update build script
pnpfile.js --> check for jquery.i18n
shrinkwrap.yaml --> all depedencies from pnpm

Closes https://github.com/coala/gci-leaders/issues/168

2018-11-06 14:59 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451404050">View build log</a>

###### TravisBuddy Request Identifier: 8da83e90-e1d4-11e8-85e1-b7338bde0197

2018-11-06 15:02 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451412683">View build log</a>

###### TravisBuddy Request Identifier: 0ad7f950-e1d5-11e8-85e1-b7338bde0197

2018-11-06 15:08 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451415533">View build log</a>

###### TravisBuddy Request Identifier: c807d400-e1d5-11e8-85e1-b7338bde0197

2018-11-06 15:13 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451417608">View build log</a>

###### TravisBuddy Request Identifier: 80de1890-e1d6-11e8-85e1-b7338bde0197

2018-11-06 15:58 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451438578">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][15:56:33] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][15:56:34] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][15:57:47] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][15:57:47] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][15:57:47] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][15:57:47] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
[DEBUG][15:57:47] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][15:57:48] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][15:57:48] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][15:57:48] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-06 17:47 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451486866">View build log</a>

###### TravisBuddy Request Identifier: fcfd1a10-e1eb-11e8-85e1-b7338bde0197

2018-11-06 17:51 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451489501">View build log</a>

###### TravisBuddy Request Identifier: 92a68c40-e1ec-11e8-85e1-b7338bde0197

2018-11-06 17:51 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451481483">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][17:49:51] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][17:49:52] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][17:50:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][17:50:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][17:50:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][17:50:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:50:59] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
[DEBUG][17:51:00] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][17:51:00] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][17:51:00] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][17:51:00] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-06 18:12 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451498008">View build log</a>

###### TravisBuddy Request Identifier: 7c415590-e1ef-11e8-85e1-b7338bde0197

2018-11-06 18:15 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451499558">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:15:45] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[WARNING][18:15:45] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][18:15:45] coala will not run any analysis. Did you forget to give the `--bears` argument?
```

</details>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-06T18_15_46_072Z-debug.log
```

</details>


<details>
  <summary>
    <strong>
     .&#x2F;.ci&#x2F;deploy.sh
    </strong>
  </summary>

```
/home/travis/.travis/job_stages: line 104: ./.ci/deploy.sh: No such file or directory
```

</details>


###### TravisBuddy Request Identifier: fba5a390-e1ef-11e8-85e1-b7338bde0197

2018-11-06 18:20 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451501723">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:20:45] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[WARNING][18:20:45] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][18:20:45] coala will not run any analysis. Did you forget to give the `--bears` argument?
```

</details>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-06T18_20_45_628Z-debug.log
```

</details>


<details>
  <summary>
    <strong>
     .&#x2F;.ci&#x2F;deploy.sh
    </strong>
  </summary>

```
/home/travis/.travis/job_stages: line 104: ./.ci/deploy.sh: No such file or directory
```

</details>


###### TravisBuddy Request Identifier: ae3eec00-e1f0-11e8-85e1-b7338bde0197

2018-11-06 18:25 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451503808">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:24:32] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[WARNING][18:24:32] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][18:24:32] coala will not run any analysis. Did you forget to give the `--bears` argument?
```

</details>


<details>
  <summary>
    <strong>
     .&#x2F;.ci&#x2F;deploy.sh
    </strong>
  </summary>

```
/home/travis/.travis/job_stages: line 104: ./.ci/deploy.sh: No such file or directory
```

</details>


###### TravisBuddy Request Identifier: 4e95d3d0-e1f1-11e8-85e1-b7338bde0197

2018-11-06 18:33 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451508740">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:32:57] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[WARNING][18:32:57] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][18:32:57] coala will not run any analysis. Did you forget to give the `--bears` argument?
```

</details>


<details>
  <summary>
    <strong>
     .&#x2F;.ci&#x2F;deploy.sh
    </strong>
  </summary>

```
/home/travis/.travis/job_stages: line 104: ./.ci/deploy.sh: No such file or directory
```

</details>


###### TravisBuddy Request Identifier: 772aa9a0-e1f2-11e8-85e1-b7338bde0197

2018-11-06 18:38 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451509845">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][18:35:45] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][18:35:45] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][18:36:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][18:36:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][18:36:59] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][18:36:59] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
[DEBUG][18:36:59] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][18:37:00] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][18:37:00] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][18:37:00] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-06 19:10 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451523106">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][19:07:19] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][19:07:20] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][19:09:08] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:09:08] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][19:09:08] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:09:08] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:08] Running bear SpaceConsistencyBear...
[DEBUG][19:09:09] Running bear SpaceConsistencyBear...
[DEBUG][19:09:09] Running bear SpaceConsistencyBear...
[DEBUG][19:09:09] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][19:09:09] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][19:09:09] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][19:09:09] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-06 19:13 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451509845">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][19:11:21] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][19:11:22] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][19:12:42] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:12:42] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][19:12:42] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:12:42] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][19:12:42] Running bear SpaceConsistencyBear...
[DEBUG][19:12:42] Running bear SpaceConsistencyBear...
[DEBUG][19:12:42] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
[DEBUG][19:12:43] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][19:12:43] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][19:12:43] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][19:12:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-06 19:20 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451526808">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][19:18:00] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][19:18:01] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][19:19:03] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:19:03] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][19:19:04] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][19:19:04] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
[DEBUG][19:19:04] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][19:19:05] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][19:19:05] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][19:19:05] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-06 23:29 UTC, andrewda requested changes

2018-11-06 23:29 UTC, andrewda commented on .travis.yml
> +  - cd jquery.i18n
The previous two lines should be shortened to

```
- cd node_modules/jquery.i18n
```

2018-11-06 23:29 UTC, andrewda commented on .travis.yml
> +  - cd ..
This can be shortened to

```
- cd ../../..
```

2018-11-06 23:29 UTC, andrewda commented on .travis.yml
> +  - git clone --recurse-submodules https://github.com/santhoshtr/CLDRPluralRuleParser.git
coala is angry that this line is too long

2018-11-07 04:03 UTC, jayvdb requested changes

2018-11-07 04:03 UTC, jayvdb commented on package.json
> +    "pnpm": "2.17.7",
this isnt needed, as it is optional --- just like npm isnt listed here , because it isnt a dependency -- no code in this package depends on code from npm or pnpm.  They are just tools.

2018-11-07 04:03 UTC, jayvdb commented on .travis.yml
> +  - mkdir libs
you can do

```yaml
- mkdir -p node_modules/jquery.i18n/libs`
- cd node_modules/jquery.i18n/libs
- git clone ...
- cd -
- pnpm install
```

2018-11-07 08:14 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451765616">View build log</a>

###### TravisBuddy Request Identifier: 27896490-e265-11e8-a645-4b1061a8d41c

2018-11-07 08:18 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451766250">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][08:18:13] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[WARNING][08:18:13] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][08:18:13] coala will not run any analysis. Did you forget to give the `--bears` argument?
```

</details>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
npm ERR! path /home/travis/build/coala/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/travis/build/coala/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T08_18_13_701Z-debug.log
```

</details>


<details>
  <summary>
    <strong>
     .&#x2F;.ci&#x2F;deploy.sh
    </strong>
  </summary>

```
/home/travis/.travis/job_stages: line 104: ./.ci/deploy.sh: No such file or directory
```

</details>


###### TravisBuddy Request Identifier: ac56e3f0-e265-11e8-a645-4b1061a8d41c

2018-11-07 08:23 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451767208">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][08:21:29] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][08:21:30] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][08:22:42] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][08:22:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][08:22:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][08:22:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
[DEBUG][08:22:43] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][08:22:44] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][08:22:44] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][08:22:44] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-07 08:27 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451768763">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][08:26:40] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[WARNING][08:26:40] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][08:26:40] coala will not run any analysis. Did you forget to give the `--bears` argument?
```

</details>


<details>
  <summary>
    <strong>
     .&#x2F;.ci&#x2F;deploy.sh
    </strong>
  </summary>

```
/home/travis/.travis/job_stages: line 104: ./.ci/deploy.sh: No such file or directory
```

</details>


###### TravisBuddy Request Identifier: f2280250-e266-11e8-a645-4b1061a8d41c

2018-11-07 08:32 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451769843">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][08:30:40] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][08:30:41] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][08:31:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][08:31:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][08:31:43] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][08:31:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
[DEBUG][08:31:43] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][08:31:44] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[WARNING][08:31:44] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[DEBUG][08:31:44] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twit [...]

2018-11-07 09:42 UTC, jayvdb requested changes
needs a tidy up

2018-11-07 09:42 UTC, jayvdb commented on .travis.yml
> +
remove extra blank line

2018-11-07 09:42 UTC, jayvdb commented on .travis.yml
> +  - mkdir libs
not done yet

2018-11-07 09:42 UTC, jayvdb commented on package.json
> +    "pnpm": "2.17.7",
not removed yet

2018-11-07 09:42 UTC, jayvdb commented on package.json
> +    "iconv-lite": "^0.4.24",
this should be moved into pnpmfile.js 

which dependency has a dependency on iconv-lite ?

2018-11-07 09:42 UTC, jayvdb commented on pnpmfile.js
> +      pkg.dependencies['jquery-i18n'] = 'github:wikimedia/jquery.i18n'
can you recheck this is necessary ?

2018-11-07 10:08 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451804622">View build log</a>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
> gci-leaders@1.0.0 build /home/travis/build/coala/gci-leaders
> npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate


> gci-leaders@1.0.0 bundle /home/travis/build/coala/gci-leaders
> NODE_ENV=production webpack --progress

module.js:538
    throw err;
    ^

Error: Cannot find module 'jquery.i18n/libs/CLDRPluralRuleParser/src/CLDRPluralRuleParser'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/home/travis/build/coala/gci-leaders/webpack.config.js:27:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/yargs/8.0.2/node_modules/yargs/yargs.js:533:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 bundle: `NODE_ENV=production webpack --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T10_08_40_821Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 build: `npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T10_08_40_837Z-debug.log
```

</details>


###### TravisBuddy Request Identifier: 1a406940-e275-11e8-a645-4b1061a8d41c

2018-11-07 10:14 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451806855">View build log</a>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 bundle: `NODE_ENV=production webpack --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T10_14_34_756Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 build: `npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T10_14_34_772Z-debug.log
```

</details>


###### TravisBuddy Request Identifier: ed744070-e275-11e8-a645-4b1061a8d41c

2018-11-07 14:10 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451901683">View build log</a>

###### TravisBuddy Request Identifier: d9fc6a10-e296-11e8-a645-4b1061a8d41c

2018-11-07 14:18 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451902790">View build log</a>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
> gci-leaders@1.0.0 build /home/travis/build/coala/gci-leaders
> npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate


> gci-leaders@1.0.0 bundle /home/travis/build/coala/gci-leaders
> NODE_ENV=production webpack --progress

module.js:538
    throw err;
    ^

Error: Cannot find module 'jquery.i18n/libs/CLDRPluralRuleParser/src/CLDRPluralRuleParser'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/home/travis/build/coala/gci-leaders/webpack.config.js:27:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/yargs/8.0.2/node_modules/yargs/yargs.js:533:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 bundle: `NODE_ENV=production webpack --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T14_18_02_309Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 build: `npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T14_18_02_330Z-debug.log
```

</details>


###### TravisBuddy Request Identifier: f0188d00-e297-11e8-a645-4b1061a8d41c

2018-11-07 14:24 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451906746">View build log</a>


<details>
  <summary>
    <strong>
     pnpm run build
    </strong>
  </summary>

```
> gci-leaders@1.0.0 build /home/travis/build/coala/gci-leaders
> npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate


> gci-leaders@1.0.0 bundle /home/travis/build/coala/gci-leaders
> NODE_ENV=production webpack --progress

module.js:538
    throw err;
    ^

Error: Cannot find module 'jquery.i18n/libs/CLDRPluralRuleParser/src/CLDRPluralRuleParser'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/home/travis/build/coala/gci-leaders/webpack.config.js:27:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/webpack/3.12.0/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/home/travis/build/coala/gci-leaders/node_modules/.registry.npmjs.org/yargs/8.0.2/node_modules/yargs/yargs.js:533:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 bundle: `NODE_ENV=production webpack --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T14_24_18_759Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gci-leaders@1.0.0 build: `npm run bundle && npm run gather && npm run scrape && npm run planet && npm run main && npm run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gci-leaders@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-07T14_24_18_778Z-debug.log
```

</details>


###### TravisBuddy Request Identifier: d08eb580-e298-11e8-a645-4b1061a8d41c

2018-11-07 14:38 UTC, TravisBuddy commented
Hey @SerekKiri,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;451915961">View build log</a>

###### TravisBuddy Request Identifier: be721a70-e29a-11e8-a645-4b1061a8d41c

2018-11-07 14:48 UTC, TravisBuddy commented
## Travis tests have failed

Hey @SerekKiri,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;451917308">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][14:46:42] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][14:46:43] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
```

</details>


###### TravisBuddy Request Identifier: 25883860-e29c-11e8-a645-4b1061a8d41c

2018-11-07 15:10 UTC, jayvdb commented on .travis.yml
> +  - mkdir libs
decided to not do this

2018-11-07 15:10 UTC, jayvdb approved these changes

2018-11-07 15:11 UTC, jayvdb commented
ack https://github.com/coala/gci-leaders/pull/170/commits/565304128ed5ff8a79cf4dc7c328525dd3b58f5f https://github.com/coala/gci-leaders/pull/170/commits/0d06cfbeebc9f9a80e1c705437be04ee0c2d576b

2018-11-07 15:11 UTC, jayvdb commented
@gitmate-bot ff

2018-11-07 15:17 UTC, jayvdb commented
@gitmate-bot ff

2018-11-07 15:18 UTC, merged