Added Sinhala translation
coala/gci-leaders pull request #174
Opened 2018-12-15 19:38 UTC by STEdirisuriya

Added Sinhala Translation
Issue #125 , #124

2018-12-15 19:52 UTC, TravisBuddy commented
Hey @STEdirisuriya,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;builds&#x2F;468481214">View build log</a>

###### TravisBuddy Request Identifier: f454f060-00a2-11e9-b792-3f85a2f5cc5a

2018-12-16 14:17 UTC, utkarsh2102 requested changes
Hey,
- You need to follow the [commit guidelines](https://coala.io/commit).
- Change `Added` to `Add` in the title.
- I, also, suggest reading the [Newcomer's Guide](https://coala.io/newcomer).

2018-12-16 20:29 UTC, TravisBuddy commented
## Travis tests have failed

Hey @STEdirisuriya,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;coala&#x2F;gci-leaders&#x2F;jobs&#x2F;468750302">View build log</a>


<details>
  <summary>
    <strong>
     coala --non-interactive -V
    </strong>
  </summary>

```
[WARNING][20:27:13] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
[DEBUG][20:27:13] Platform Linux -- Python 3.6.3, coalib 0.11.0
Executing section all...
[DEBUG][20:28:13] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/si.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][20:28:13] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
Executing section all.whitespace...
[DEBUG][20:28:13] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-leaders/src/js/utils.js
/home/travis/build/coala/gci-leaders/src/js/locale.js
/home/travis/build/coala/gci-leaders/src/js/app.js
/home/travis/build/coala/gci-leaders/src/js/twitter.js
/home/travis/build/coala/gci-leaders/src/js/bootstrap.js
/home/travis/build/coala/gci-leaders/package.json
/home/travis/build/coala/gci-leaders/static/i18n/es.json
/home/travis/build/coala/gci-leaders/static/i18n/pl.json
/home/travis/build/coala/gci-leaders/static/i18n/nb_NO.json
/home/travis/build/coala/gci-leaders/static/i18n/si.json
/home/travis/build/coala/gci-leaders/static/i18n/en.json
/home/travis/build/coala/gci-leaders/src/styles/main.css
/home/travis/build/coala/gci-leaders/.travis.yml
/home/travis/build/coala/gci-leaders/templates/planet.html
/home/travis/build/coala/gci-leaders/templates/main.html
/home/travis/build/coala/gci-leaders/templates/pre2017.html
/home/travis/build/coala/gci-leaders/.eslintrc
[DEBUG][20:28:13] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
[DEBUG][20:28:13] Running bear SpaceConsistencyBear...
Executing section all.linelength...
[WARNING][20:28:14] No files matching '/home/travis/build/coala/gci-leaders/**.json' were found.
[WARNING][20:28:14] No files matching '/home/travis/build/coala/gci-leaders/**.html' were found.
[DEBUG][20:28:14] Files that will be checked:
/home/travis/build/coala/gci-leaders/webpack.config.js
/home/travis/build/coala/gci-leaders/tests/lib/pre2017.test.js
/home/travis/build/coala/gci-leaders/tests/lib/generate.test.js
/home/travis/build/coala/gci-leaders/tests/lib/gather.test.js
/home/travis/build/coala/gci-leaders/tests/lib/scrape.test.js
/home/travis/build/coala/gci-leaders/tests/lib/rss.test.js
/home/travis/build/coala/gci-leaders/tests/lib/planet.test.js
/home/travis/build/coala/gci-leaders/pnpmfile.js
/home/travis/build/coala/gci-leaders/lib/generate.js
/home/travis/build/coala/gci-leaders/lib/planet.js
/home/travis/build/coala/gci-leaders/lib/utils.js
/home/travis/build/coala/gci-leaders/lib/queries/index.js
/home/travis/build/coala/gci-leaders/lib/scrape.js
/home/travis/build/coala/gci-leaders/lib/rss.js
/home/travis/build/coala/gci-leaders/lib/pre2017.js
/home/travis/build/coala/gci-leaders/lib/main.js
/home/travis/build/coala/gci-leaders/lib/gather.js
/home/travis/build/coala/gci-lead [...]

2018-12-26 20:12 UTC, STEdirisuriya commented
I need a help for solve it.

2019-01-09 08:17 UTC, closed without merging