Solving issue #23: randomising order of participants
coala/gci-leaders pull request #40
Opened 2017-12-06 13:14 UTC by falafel72

Added client-side javascript to allow for randomising order of leaderboard.

2017-12-06 13:35 UTC, blazeu requested changes
After you're done, run `coala` to format the code https://coala.io.

---

```
$(npm bin)/prettier --single-quote --no-semi --trailing-comma es5 --write static/js/scripts.js
```
^ if you can't run coala.

2017-12-06 13:35 UTC, blazeu commented on static/js/scripts.js
> +window.onload = function() {
No need to put on `onload`.
The script is already on the bottom of the page.

2017-12-06 13:35 UTC, blazeu commented on static/js/scripts.js
> +        //shuffle each leaderboard
space after //

2017-12-06 13:45 UTC, blazeu commented
Also, keep in mind to not push changes from your master branch - create a new branch instead. Might lead to some conflicts. Refer http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-3-creating-a-fork-and-testing-your-changes. :smile:

2017-12-06 14:10 UTC, falafel72 commented
I'll be sure to keep that in mind 👍 
Everything should be fixed now.

2017-12-06 14:18 UTC, blazeu commented
Nice. Squash into a single commit 
api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

2017-12-06 14:37 UTC, blazeu requested changes
Format your commit message according to https://coala.io/commit

2017-12-06 14:47 UTC, falafel72 commented
Things got a little awkward cause I originally cloned it and forgot to fork...should be fine now though.

2017-12-06 14:47 UTC, blazeu commented
No, still 5 commit :/
You can ask in our chatroom @ https://coala.zulipchat.com/ if you're confused :)

2017-12-06 14:48 UTC, blazeu commented
Added -> Add

2017-12-06 15:11 UTC, falafel72 commented
Just tried using `git reset --soft`, did that work?

2017-12-06 15:26 UTC, blazeu commented
Run `git rebase -i HEAD~7`

7 is your commit count in this case.

Then, you want to replace `pick` to `squash`, except for the first one.

Hit save and tidy up your commit message so that it only contains your main commit.

2017-12-06 16:17 UTC, jayvdb commented
Comment on 9a4648c91e8742e9e93ac348c758efa8f4ad4eea, file scrap.js, line 34.

Line contains following spacing inconsistencies:
- Trailing whitespaces.

*Origin: SpaceConsistencyBear, Section: `all.whitespace`.*

The issue can be fixed by applying the following patch:

```diff
--- a/tmp/tmpo1u7h43c/scrap.js
+++ b/tmp/tmpo1u7h43c/scrap.js
@@ -31,7 +31,7 @@
 
 ;(async () => {
   const data = await fetchOrgsWithLeaders()
-  
+
   // sort data by completed_task_instance_count
   data.sort((a, b) => 
     b.completed_task_instance_count - a.completed_task_instance_count
```

2017-12-06 16:17 UTC, jayvdb commented
Comment on 9a4648c91e8742e9e93ac348c758efa8f4ad4eea, file scrap.js, line 36.

Line contains following spacing inconsistencies:
- Trailing whitespaces.

*Origin: SpaceConsistencyBear, Section: `all.whitespace`.*

The issue can be fixed by applying the following patch:

```diff
--- a/tmp/tmpo1u7h43c/scrap.js
+++ b/tmp/tmpo1u7h43c/scrap.js
@@ -33,7 +33,7 @@
   const data = await fetchOrgsWithLeaders()
   
   // sort data by completed_task_instance_count
-  data.sort((a, b) => 
+  data.sort((a, b) =>
     b.completed_task_instance_count - a.completed_task_instance_count
   )
 
```

2017-12-06 16:17 UTC, jayvdb commented on package.json
> -    "ncp": "^2.0.0",
This file does not contain parsable JSON. Expecting ',' delimiter.

*Origin: JSONFormatBear, Section: `json`.*

2017-12-06 16:17 UTC, jayvdb commented
Comment on 9a4648c91e8742e9e93ac348c758efa8f4ad4eea, file .travis.yml, line 10.

too few spaces before comment (comments)

*Origin: YAMLLintBear, Section: `yaml`.*

2017-12-06 16:17 UTC, jayvdb commented
Comment on 9a4648c91e8742e9e93ac348c758efa8f4ad4eea, file .travis.yml, line 12.

truthy value is not quoted (truthy)

*Origin: YAMLLintBear, Section: `yaml`.*

2017-12-06 16:20 UTC, falafel72 commented
Seems like the problem is that I've got merge conflicts from merging my fork and my clone and I undo the merge every time I squash all my commits. Is there a way I can integrate the changes made by the merge into my squashed commits?

2017-12-06 17:30 UTC, blazeu commented
Well I did tell the wrong instruction :disappointed: 

What you could do now is checkout this commit https://github.com/coala/gci-leaders/pull/40/commits/9a4648c91e8742e9e93ac348c758efa8f4ad4eea and back up your modified files.

Add this repo as `upstream` remote and then `git fetch upstream`

Do `git reset --hard upstream/master` (this will remove your change, so make sure you have a backup).

Then apply your changes manually.

Do not push until your commit count is exactly 1.

You can ask more here https://coala.zulipchat.com

2017-12-07 00:20 UTC, jayvdb commented on static/js/app.js
> +});
Line contains following spacing inconsistencies:
- No newline at EOF.

*Origin: SpaceConsistencyBear, Section: `all.whitespace`.*

The issue can be fixed by applying the following patch:

```diff
--- a/tmp/tmpd5h9drm4/static/js/app.js
+++ b/tmp/tmpd5h9drm4/static/js/app.js
@@ -34,4 +34,4 @@
   for(var i = orgList.children.length; i >= 0; i--) {
     orgList.appendChild(orgList.children[Math.random()*i | 0]);
   }
-});+});
```

2017-12-07 00:33 UTC, falafel72 commented
Thanks, looks like it's finally working.

2017-12-07 00:53 UTC, andrewda commented
ack 3aafa26998d5505f12385ee8728b6eb913755ceb

2017-12-07 03:55 UTC, blazeu approved these changes

2017-12-07 03:56 UTC, merged