Add Twitter GCI hashtags stream
coala/gci-leaders pull request #45
Opened 2017-12-07 19:23 UTC by LifetimeAlone

Add Twitter widget, streaming GCI hashtags posts.

2017-12-07 19:23 UTC, jayvdb commented on static/css/main.css
> +.twitter  {
Rule is empty. (empty-rules)

*Origin: CSSLintBear, Section: `css`.*

2017-12-07 19:23 UTC, LifetimeAlone commented
I'm good at web, I need help to place it in the correct place.
Would be create, if somebody helps me :)

2017-12-07 19:27 UTC, LifetimeAlone commented
It also doesn't look like it should :( 

![](https://coala.zulipchat.com/user_uploads/1208/cxchzbZPaHePmEWiYo_a-oTt/pasted_image.png)

2017-12-07 20:49 UTC, jayvdb commented on static/css/main.css
> +.twitter {
Rule doesn't have all its properties in alphabetical order. (order-alphabetical)

*Origin: CSSLintBear, Section: `css`.*

2017-12-08 04:15 UTC, blazeu requested changes
Maybe put the widget at the bottom (after orgs with no leaders).
Lets test it.

2017-12-08 04:15 UTC, blazeu commented on templates/main.html
> +      <script src="static/js/twitter.js"></script>
The `<script>` tag can be put on the bottom of the body

2017-12-08 04:15 UTC, blazeu commented on templates/main.html
> +      </a>
It's not closing any `<a>` tag :P
Remove it.

2017-12-08 06:51 UTC, blazeu requested changes

2017-12-08 06:51 UTC, blazeu commented on static/css/main.css
> +}
Lets go with 100% width instead of centering

Try the selector `.twitter > iframe`

2017-12-08 07:22 UTC, jayvdb commented on static/css/main.css
> +.twitter  {
Rule is empty. (empty-rules)

*Origin: CSSLintBear, Section: `css`.*

2017-12-08 07:22 UTC, jayvdb commented on static/css/main.css
> +  .twirrer > iframe;
Expected RBRACE at line 48, col 3. (errors)

*Origin: CSSLintBear, Section: `css`.*

2017-12-08 07:27 UTC, blazeu requested changes

2017-12-08 07:27 UTC, blazeu commented on templates/main.html
> +    <div class="'twitter">
Remove `'`

2017-12-08 07:31 UTC, jayvdb commented on static/css/main.css
> +.twitter > iframe {
Rule doesn't have all its properties in alphabetical order. (order-alphabetical)

*Origin: CSSLintBear, Section: `css`.*

2017-12-08 07:35 UTC, blazeu requested changes

2017-12-08 07:35 UTC, blazeu commented on static/css/main.css
> +  text-align: center;
No need

2017-12-08 07:35 UTC, blazeu commented on static/css/main.css
> +  width: 100%;
Try `100% !important` 

It's being overridden by the inline styling :/
if you check the devtool (inspect element)

2017-12-08 07:36 UTC, blazeu commented
Now you need to rebase for the new design :sparkles:

2017-12-08 08:27 UTC, jayvdb commented on static/css/main.css
> +  width: 100% !important;
Use of !important (important)

*Origin: CSSLintBear, Section: `css`.*

2017-12-08 08:32 UTC, blazeu commented on templates/main.html
> +         data-widget-id="938830025809432577">Tweets about GCI
I see no "Tweets about GCI" in the result

2017-12-08 08:33 UTC, blazeu commented on templates/main.html
> +         data-widget-id="938830025809432577">Tweets about GCI
probably just remove it since there's a big #googlecodein

2017-12-08 08:34 UTC, blazeu commented on static/css/main.css
> +  width: 100% !important;
Try
`# Ignore CSSLintBear`
Here

2017-12-08 08:35 UTC, LifetimeAlone commented on static/css/main.css
> +  width: 100% !important;
Didn't it work like this?

2017-12-08 08:35 UTC, LifetimeAlone commented on static/css/main.css
> +  width: 100% !important;
Gitmate shows no mistake now

2017-12-08 08:37 UTC, blazeu commented on static/css/main.css
> +  width: 100% !important;
See my chat on Zulip.

2017-12-08 08:41 UTC, blazeu approved these changes

2017-12-08 08:42 UTC, blazeu commented
ack https://github.com/coala/gci-leaders/pull/45/commits/9defd0a7bf1a1dc964e661843f1c7fefc52e76cc

2017-12-08 08:43 UTC, merged