Get better Lighthouse score in a11y and performance
coala/gci-leaders pull request #78
Opened 2017-12-12 18:29 UTC by myfrom

I did a few things (all mentioned in the commits) to improve the Lighthouse score. There are a few differences between my tests and the test file from https://gci-leaders.netlify.com/ that were caused by my development environment and the fact that machine is fairly slow.

I also changed the output of /static from /out/static to the root of /out as we were discussing in #55

Here are test results before and after:
[tests.zip](https://github.com/coala/gci-leaders/files/1552817/tests.zip)

Related to #55, part of [GCI task](https://codein.withgoogle.com/dashboard/task-instances/5311708543320064/)

2017-12-12 23:20 UTC, andrewda reviewed
Not sure why Lighthouse didn't complain about this, but the RocketChat logo can probably be shrunk to 72px.

2017-12-13 01:57 UTC, blazeu commented on templates/main.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes">
I think `maximum-scale=5.0, user-scalable=yes` is not needed now.

2017-12-13 02:01 UTC, blazeu requested changes
Favicon has white border, looks ugly, remove them.

Also, I don't know if this is accurate or not, but checked via https://realfavicongenerator.net/favicon_checker
![image](https://user-images.githubusercontent.com/1438859/33918068-1399d4da-dfe4-11e7-85ea-bee6f6bc4f28.png)

favicon.ico should contain multiple sizes (in the same file).

2017-12-13 02:03 UTC, blazeu requested changes
Commit message should be in imperative present tense https://coala.io/commit
e.g. Improved ~> Improve

2017-12-13 07:47 UTC, jayvdb commented
@myfrom , please undo your merge commit.  We do proper rebases at coala.  see http://coala.io/rebase .

Also please in future do not create pull requests from your 'master' branch. (but please do not close this PR; we'll get this one fixed & merged ; ask us for help on Zulip)

2017-12-13 16:02 UTC, myfrom commented
@andrewda @jayvdb @blazeu Fixed everything

2017-12-13 16:20 UTC, blazeu commented
if you turn the GCI logo on the website to png or vector with transparent background, it might reduce the size. Try it first.

2017-12-13 16:22 UTC, blazeu commented
Also your branch is still outdated, you need to rebase. http://coala.io/rebase

2017-12-13 16:38 UTC, myfrom commented
Oh, sorry, should be OK now.

2017-12-13 16:47 UTC, blazeu requested changes
Some of the images are broken. See https://deploy-preview-78--gci-leaders.netlify.com/ (deploy/netlify on below)

And wiki icons are gone, you need to add them back, resize if needed, and add the `alt`

2017-12-13 18:46 UTC, myfrom commented
Oh, sorry, missed those new icons. I updated them and basically have everything working, I'll upload tomorrow.

@blazeu
But I have one big problem: someone made a script that instead of creating new data.json takes the current one. The current one is pointing to images in static which now are in root. How should I overcome this? Delete this script?

2017-12-13 19:02 UTC, andrewda commented
We should add a CACHE_VERSION and increment it whenever anything breaking occurs to the data. This will let us bust the cache if it becomes stale. I can do this in a few hours.

2017-12-14 02:36 UTC, blazeu commented
@andrewda why not just remove the image url from the JSON and then rely on the chat platform name.

2017-12-14 03:21 UTC, andrewda commented
That would be one option, but adding a CACHE_VERSION would allow us to avoid this problem entirely in the future, such as if a new key were added or an existing one were taken away.

2017-12-14 05:36 UTC, blazeu commented
In the mean time, I'm gonna run `npm run build:clean` on netlify so that @myfrom can continue his work.

2017-12-14 16:00 UTC, myfrom commented
Should be OK now if we run it through `$ npm run build:clean`

2017-12-15 03:34 UTC, blazeu commented
Okay.

After this one, I want you sent another PR to `gh-pages` to delete `data.(js|min.js|yml)` to remove those old keys.

2017-12-15 03:34 UTC, blazeu approved these changes

2017-12-15 03:38 UTC, blazeu commented
ack https://github.com/coala/gci-leaders/pull/78/commits/be803a965a8cef653d8231c0e66843fce0dad980 https://github.com/coala/gci-leaders/pull/78/commits/f95ffaf214f529b69de444760653ce75f2621410 https://github.com/coala/gci-leaders/pull/78/commits/cf4a35d4e13be80a773d0b316be639e1bb6780a7 https://github.com/coala/gci-leaders/pull/78/commits/206a75c24f14f10f744a574c87920d6d07dfe218

2017-12-15 12:50 UTC, merged