scrape.js: Handle username changes and deletions
coala/gci-leaders pull request #94
Opened 2017-12-18 17:06 UTC by andrewda

Prior to this, if a user's GitHub account was cached, it would be
assumed to be correct for all future builds. However, this is not
the case if the user has changed or deleted their account. This
will verify that the cached username exists before using it, and
rerun the username finding code if it does not exist.

Closes https://github.com/coala/gci-leaders/issues/93

2017-12-18 17:47 UTC, blazeu requested changes

2017-12-18 17:47 UTC, blazeu commented on lib/scrape.js
> +  return res.status === 200 ? true : false
=== will return boolean, no need to do ternary.

2017-12-19 01:05 UTC, jayvdb requested changes

2017-12-19 01:05 UTC, jayvdb commented on lib/scrape.js
> +      updated: Date.now(),
you're abusing this function.  A find function will always have an `updated` of "now", so it is redundant and annoying to be returning that to the caller.

the storing of cache information doesnt belong in this function.

2017-12-19 01:05 UTC, jayvdb commented on lib/scrape.js
> +        if (
move this out to a new function so as to not over-complicate this function with GitHub stuff , and also a new function will be testable.

2017-12-19 02:08 UTC, jayvdb commented on lib/scrape.js
> +  if (username) {
unnecessary change here

2017-12-19 02:10 UTC, jayvdb commented on lib/scrape.js
> +async function fetchUserFromCache(user, existingUser, organization) {
I would name this something like `freshenUserGitHubCache`

2017-12-19 02:11 UTC, jayvdb commented on lib/scrape.js
> +function checkCacheExpired(user) {
Also mention GitHub in this function name

2017-12-19 02:12 UTC, jayvdb commented on lib/scrape.js
> +        return {
this branch could also use `fetchUserFromCache`, by with `existingUser` being undefined.

2017-12-19 02:24 UTC, jayvdb approved these changes

2017-12-19 03:02 UTC, blazeu approved these changes

2017-12-19 03:02 UTC, blazeu commented
Just need a rebase.

2017-12-19 10:26 UTC, blazeu commented
ack https://github.com/coala/gci-leaders/pull/94/commits/209b9f482d0d3e3a97c01f6c2ebea7d17c50492c

2017-12-19 10:26 UTC, merged